# Generated by Django 3.0.6 on 2020-05-20 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('internal_id', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('clinic_question', models.TextField()),
                ('professional_question', models.TextField()),
                ('questionnaire', models.ManyToManyField(blank=True, to='questions.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Choice')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Choice')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Clinic')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Question')),
            ],
        ),
    ]
