# Generated by Django 3.0.6 on 2020-05-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='Australia', max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_pay_max', models.IntegerField(null=True)),
                ('hourly_pay_min', models.IntegerField(null=True)),
                ('annual_pay_max', models.IntegerField(null=True)),
                ('annual_pay_min', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('AUD', 'AUD')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work_type', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Nurse', 'Nurse')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Clinic')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalFlaggedProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professionalflaggedprofessional_professional', to='professionals.Professional')),
                ('professional_noted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professionalflaggedprofessional_professional_noted', to='professionals.Professional')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalFlaggedClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Clinic')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
            ],
        ),
    ]
