# Generated by Django 2.1.7 on 2019-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_auto_20190226_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
