# Generated by Django 2.1.7 on 2019-03-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_auto_20190305_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='professional',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
