# Generated by Django 3.0.6 on 2020-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_import_professionals_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='bulk_billing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
