# Generated by Django 2.1.7 on 2019-03-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20190306_0952'),
        ('professionals', '0004_auto_20190306_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='current_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='clinics.Clinic'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='current_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Organisation'),
        ),
        migrations.RemoveField(
            model_name='professional',
            name='starred_clinic',
        ),
        migrations.AddField(
            model_name='professional',
            name='starred_clinic',
            field=models.ManyToManyField(blank=True, null=True, related_name='professional_starred', to='clinics.Clinic'),
        ),
    ]
