# Generated by Django 2.1.7 on 2019-03-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_auto_20190306_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='professional',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Area'),
        ),
    ]
