# Generated by Django 2.1.7 on 2019-03-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_auto_20190306_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.CharField(default='Australia', max_length=20),
        ),
        migrations.AlterField(
            model_name='professional',
            name='previous_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.Role'),
        ),
    ]
