# Generated by Django 2.2.2 on 2019-06-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20190622_0941'),
        ('professionals', '0008_auto_20190317_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_pay_max', models.IntegerField()),
                ('hourly_pay_min', models.IntegerField()),
                ('annual_pay_max', models.IntegerField()),
                ('annual_pay_min', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work_type', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Nurse', 'Nurse')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Clinic')),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='current_clinic',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='current_organisation',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='previous_roles',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profession',
        ),
        migrations.AddField(
            model_name='professional',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='professional',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='starred_clinic',
            field=models.ManyToManyField(blank=True, to='clinics.Clinic'),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AddField(
            model_name='role',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional'),
        ),
        migrations.AddField(
            model_name='role',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Rate'),
        ),
    ]
