# Generated by Django 2.2.2 on 2019-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_auto_20190622_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='annual_pay_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='annual_pay_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='hourly_pay_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='hourly_pay_min',
            field=models.IntegerField(null=True),
        ),
    ]
