# Generated by Django 3.0.6 on 2020-07-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0010_auto_20200703_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalgroup',
            name='display_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
