# Generated by Django 3.0.6 on 2020-07-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_professionalgroup_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalgroup',
            name='display_name',
        ),
    ]
