# Generated by Django 3.0.6 on 2020-07-04 05:10

from django.db import migrations, models
import uuid


def create_professional_uuid(apps, schema_editor):
    Professional = apps.get_model("professionals", "Professional")
    for professional in Professional.objects.all():
        professional.uid = str(uuid.uuid4()).replace("-", "")
        professional.save()


def create_profession_uuid(apps, schema_editor):
    Profession = apps.get_model("professionals", "Profession")
    for profession in Profession.objects.all():
        profession.uid = str(uuid.uuid4()).replace("-", "")
        profession.save()


def create_professional_group_uuid(apps, schema_editor):
    ProfessionalGroup = apps.get_model("professionals", "ProfessionalGroup")
    for group in ProfessionalGroup.objects.all():
        group.uid = str(uuid.uuid4()).replace("-", "")
        group.save()


def create_profession_type_uuid(apps, schema_editor):
    ProfessionType = apps.get_model("professionals", "ProfessionType")
    for profession_type in ProfessionType.objects.all():
        profession_type.uid = str(uuid.uuid4()).replace("-", "")
        profession_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0012_remove_professionalgroup_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='uid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='uid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professionalgroup',
            name='uid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professiontype',
            name='uid',
            field=models.UUIDField(null=True, blank=True),
        ),

        migrations.RunPython(create_profession_uuid),
        migrations.RunPython(create_professional_uuid),
        migrations.RunPython(create_professional_group_uuid),
        migrations.RunPython(create_profession_type_uuid),

        migrations.AlterField(
            model_name='profession',
            name='uid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='uid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='professionalgroup',
            name='uid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='professiontype',
            name='uid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
