# Generated by Django 3.0.6 on 2020-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0014_auto_20200704_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='professionalgroup',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='professiontype',
            name='uid',
        ),
    ]
