# Generated by Django 3.0.6 on 2020-07-04 11:26

from django.db import migrations, models
from utils.general import create_uid


def create_professional_uid(apps, schema_editor):
    Professional = apps.get_model("professionals", "Professional")
    for professional in Professional.objects.all():
        professional.uid = create_uid()
        professional.save()


def create_profession_uid(apps, schema_editor):
    Profession = apps.get_model("professionals", "Profession")
    for profession in Profession.objects.all():
        profession.uid = create_uid()
        profession.save()


def create_professional_group_uid(apps, schema_editor):
    ProfessionalGroup = apps.get_model("professionals", "ProfessionalGroup")
    for group in ProfessionalGroup.objects.all():
        group.uid = create_uid()
        group.save()


def create_profession_type_uid(apps, schema_editor):
    ProfessionType = apps.get_model("professionals", "ProfessionType")
    for profession_type in ProfessionType.objects.all():
        profession_type.uid = create_uid()
        profession_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0015_auto_20200704_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='uid',
            field=models.CharField(max_length=32, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='uid',
            field=models.CharField(max_length=32, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professionalgroup',
            name='uid',
            field=models.CharField(max_length=32, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='professiontype',
            name='uid',
            field=models.CharField(max_length=32, null=True, blank=True),
        ),

        migrations.RunPython(create_profession_uid),
        migrations.RunPython(create_professional_uid),
        migrations.RunPython(create_professional_group_uid),
        migrations.RunPython(create_profession_type_uid),

        migrations.AlterField(
            model_name='profession',
            name='uid',
            field=models.CharField(max_length=32, unique=True, default=create_uid, editable=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='uid',
            field=models.CharField(max_length=32, unique=True, default=create_uid, editable=False),
        ),
        migrations.AlterField(
            model_name='professionalgroup',
            name='uid',
            field=models.CharField(max_length=32, unique=True, default=create_uid, editable=False),
        ),
        migrations.AlterField(
            model_name='professiontype',
            name='uid',
            field=models.CharField(max_length=32, unique=True, default=create_uid, editable=False),
        ),
    ]
