# Generated by Django 2.1.4 on 2018-12-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-50', '20-50'), ('50+', '50+')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=30)),
                ('street_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-50', '20-50'), ('50+', '50+')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('guaranteed_annual_salary', models.IntegerField()),
                ('guaranteed_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Guaranteed Hourly Rate')),
                ('guaranteed_percentage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Guaranteed Percentage')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='available_positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Role'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Location'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Organisation'),
        ),
    ]
