# Generated by Django 2.1.7 on 2019-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='size',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-50', '20-50'), ('50-200', '50-200'), ('200+', '200+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='size',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-50', '20-50'), ('50-200', '50-200'), ('200+', '200+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
