# Generated by Django 3.0.6 on 2020-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20200520_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='street_number',
            field=models.CharField(max_length=30),
        ),
    ]
