# Generated by Django 2.1.7 on 2019-03-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20190306_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='available_positions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='guaranteed_annual_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='guaranteed_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Guaranteed Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='role',
            name='guaranteed_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Guaranteed Percentage'),
        ),
    ]
