# Generated by Django 2.2.2 on 2019-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_auto_20190317_0837'),
        ('clinics', '0003_auto_20190306_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='available_positions',
        ),
        migrations.AddField(
            model_name='clinic',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='starred_professional',
            field=models.ManyToManyField(blank=True, to='professionals.Professional'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
