# Generated by Django 2.2.2 on 2019-06-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20190622_0941'),
        ('professionals', '0009_auto_20190622_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
