# Generated by Django 2.2.2 on 2019-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
