# Generated by Django 3.0.6 on 2020-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
