# Generated by Django 3.0.6 on 2020-07-04 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200704_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotesclinic',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='usernotesprofessional',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
