# Generated by Django 3.0.6 on 2020-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200704_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotesclinic',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='usernotesprofessional',
            name='uid',
        ),
    ]
