# Generated by Django 3.0.6 on 2020-10-29 04:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200704_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotesclinic',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='usernotesprofessional',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
    ]
