# Generated by Django 3.0.6 on 2020-06-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0008_auto_20200610_0619'),
        ('clinics', '0010_calculate_latitude_and_longitude_altered'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=100, unique=True)),
                ('professional', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotesProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotesClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
    ]
