# Generated by Django 3.0.6 on 2020-05-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20200520_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinics.Organisation'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='size',
            field=models.CharField(blank=True, choices=[('0-5', '0-5'), ('5-20', '5-20'), ('20-50', '20-50'), ('50-200', '50-200'), ('200+', '200+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
