# Generated by Django 3.0.6 on 2020-06-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_remove_duplicate_psychologist_profession_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.ProfessionalGroup')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
            ],
        ),
        migrations.RemoveField(
            model_name='professionalflaggedprofessional',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='professionalflaggedprofessional',
            name='professional_noted',
        ),
        migrations.DeleteModel(
            name='ProfessionalFlaggedClinic',
        ),
        migrations.DeleteModel(
            name='ProfessionalFlaggedProfessional',
        ),
    ]
