# Generated by Django 3.0.6 on 2020-06-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_auto_20200610_0619'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
    ]
