# Generated by Django 3.0.6 on 2020-07-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200614_0709'),
        ('professionals', '0009_professionalgroup_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professionalgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='professionalgroupmapping',
            unique_together={('professional', 'group')},
        ),
    ]
